/**
 * The seeded production estate.
 *
 * Every number is generated by a pure function with a fixed seed, so the dataset
 * is byte-identical on every boot. That matters for two reasons:
 *
 *  1. The demo has to be reproducible. A judge watching the recording and a judge
 *     cloning the repo must see the same 3.7x regression.
 *  2. The agent's conclusion has to be *earned* from the data rather than read off
 *     a constant. Nothing states "deployment 4c21 is the cause" — the metrics
 *     simply change shape after 15:02, the diff explains why, and the agent has to
 *     connect them.
 *
 * The estate is simulated; the MCP protocol traffic against it is not. TrueForge
 * makes real JSON-RPC calls over streamable HTTP to reach these tools.
 *
 * ## Why this file is now a shim
 *
 * The checkout regression used to be the only thing that existed, so it lived
 * here directly. It is now one of four cases in `scenarios.ts` — three of which
 * are deliberately *not* answerable by "roll back the most recent deploy", which
 * is the reflex a single-scenario estate silently rewards.
 *
 * These exports are kept, unchanged in shape and value, because the store, the
 * HTTP surface, and the existing tests all name them. They resolve to the
 * default scenario, which is the original checkout regression.
 *
 * @see scenarios.ts
 */

import { DEPLOY_AT, defaultScenario, SERVICE } from './scenarios.js';
import type { Deployment, Incident, MetricSample, ServiceHealth } from './types.js';

export { DEPLOY_AT, SERVICE };

export const buildMetrics = (): MetricSample[] => defaultScenario().buildMetrics();

export const buildDeployments = (): Deployment[] => defaultScenario().buildDeployments();

export const buildIncident = (): Incident => defaultScenario().buildIncident();

export const buildHealth = (liveDeploymentId: string): ServiceHealth =>
  defaultScenario().buildHealth(liveDeploymentId);
