/**
 * The seeded production estate.
 *
 * Every number here is generated by a pure function with a fixed seed, so the
 * dataset is byte-identical on every boot. That matters for two reasons:
 *
 *  1. The demo has to be reproducible. A judge watching the recording and a judge
 *     cloning the repo must see the same 3.7x regression.
 *  2. The agent's conclusion has to be *earned* from the data rather than read off
 *     a constant. Nothing in this file states "deployment 4c21 is the cause" — the
 *     metrics simply change shape after 15:02, the diff explains why, and the
 *     agent has to connect them.
 *
 * The estate is simulated; the MCP protocol traffic against it is not. TrueForge
 * makes real JSON-RPC calls over streamable HTTP to reach these tools.
 */

import type { Deployment, Incident, MetricSample, ServiceHealth } from './types.js';

export const SERVICE = 'checkout-api';

/** Wall-clock anchor for the whole scenario. */
export const DEPLOY_AT = Date.parse('2026-08-25T15:02:00Z');
const WINDOW_START = Date.parse('2026-08-25T14:30:00Z');
const WINDOW_MINUTES = 61;

/**
 * Deterministic jitter in [-1, 1).
 *
 * A 32-bit integer hash of the sample index — chosen over `Math.random()` so the
 * series is stable across processes, and over a hand-written table so it still
 * looks like telemetry rather than a staircase.
 */
function jitter(index: number, salt: number): number {
  let h = (index * 2654435761 + salt * 40503) | 0;
  h ^= h >>> 15;
  h = (h * 2246822519) | 0;
  h ^= h >>> 13;
  h = (h * 3266489917) | 0;
  h ^= h >>> 16;
  return (h & 0xffff) / 0x8000 - 1;
}

const round = (value: number, dp: number): number => {
  const f = 10 ** dp;
  return Math.round(value * f) / f;
};

/**
 * Golden-signal series across the incident window.
 *
 * Shape: flat baseline until the deploy, a four-minute ramp as connection pools
 * fill and retries pile up, then a new plateau. The plateau is ~3.70x baseline
 * p95 — but that ratio is a consequence of the two constants below, not an
 * assertion the agent can read.
 */
export function buildMetrics(): MetricSample[] {
  const BASE_P95 = 178;
  const PLATEAU_P95 = 658;
  const BASE_ERR = 0.004;
  const PLATEAU_ERR = 0.062;
  const RAMP_MINUTES = 4;

  const samples: MetricSample[] = [];

  for (let i = 0; i < WINDOW_MINUTES; i += 1) {
    const ts = WINDOW_START + i * 60_000;
    const minutesSinceDeploy = (ts - DEPLOY_AT) / 60_000;

    // 0 before the deploy, ramping to 1 over RAMP_MINUTES, then held.
    const progress = minutesSinceDeploy < 0 ? 0 : Math.min(1, minutesSinceDeploy / RAMP_MINUTES);
    // Ease-out so the ramp looks like saturation rather than a straight line.
    const eased = progress === 0 ? 0 : 1 - (1 - progress) ** 2;

    const p95 = BASE_P95 + (PLATEAU_P95 - BASE_P95) * eased + jitter(i, 1) * 6;
    const p50 = p95 * 0.34 + jitter(i, 2) * 3;
    const errorRate = BASE_ERR + (PLATEAU_ERR - BASE_ERR) * eased + jitter(i, 3) * 0.0009;
    const rps = 121 + jitter(i, 4) * 7;

    samples.push({
      ts: new Date(ts).toISOString(),
      p95_latency_ms: round(p95, 1),
      p50_latency_ms: round(p50, 1),
      error_rate: round(Math.max(0, errorRate), 5),
      rps: round(rps, 1),
    });
  }

  return samples;
}

/**
 * Deployment history, newest first.
 *
 * `dpl-4c21` is the regression: it raises an upstream timeout from 250ms to 30s
 * and adds three retries. Three retries against a 30-second ceiling is where the
 * latency tail comes from — a plausible change with a non-obvious consequence,
 * which is the only kind worth asking an agent to diagnose.
 */
export function buildDeployments(): Deployment[] {
  return [
    {
      id: 'dpl-4c21',
      service: SERVICE,
      version: '2026.8.25-1',
      commit_sha: 'a19f3c2',
      author: 'r.okafor',
      message: 'Raise upstream client timeout and add retries for flaky tax provider',
      deployed_at: new Date(DEPLOY_AT).toISOString(),
      status: 'live',
      changed_files: ['src/checkout/upstreamClient.ts', 'src/checkout/config.ts'],
      diff: `--- a/src/checkout/upstreamClient.ts
+++ b/src/checkout/upstreamClient.ts
@@ -10,10 +10,10 @@ import { taxProvider } from './providers/tax';

 export const upstreamClient = createClient({
   baseUrl: config.taxProviderUrl,
-  // Fail fast: the checkout path has a 400ms budget end to end.
-  timeoutMs: 250,
-  retries: 0,
+  // Tax provider has been flaky this week; be more patient with it.
+  timeoutMs: 30_000,
+  retries: 3,
   onError: (err) => logger.warn({ err }, 'tax provider call failed'),
 });

--- a/src/checkout/config.ts
+++ b/src/checkout/config.ts
@@ -22,7 +22,7 @@ export const config = {
   taxProviderUrl: env.TAX_PROVIDER_URL,
-  checkoutBudgetMs: 400,
+  checkoutBudgetMs: 400, // unchanged
 };
`,
    },
    {
      id: 'dpl-4c20',
      service: SERVICE,
      version: '2026.8.24-2',
      commit_sha: '7b2e881',
      author: 'l.marchetti',
      message: 'Emit cart-abandonment counter',
      deployed_at: '2026-08-24T11:20:00Z',
      status: 'superseded',
      changed_files: ['src/checkout/metrics.ts'],
      diff: `--- a/src/checkout/metrics.ts
+++ b/src/checkout/metrics.ts
@@ -8,3 +8,6 @@ export const checkoutStarted = counter('checkout_started_total');
+export const cartAbandoned = counter('cart_abandoned_total', {
+  help: 'Carts abandoned before payment authorisation',
+});
`,
    },
    {
      id: 'dpl-4c19',
      service: SERVICE,
      version: '2026.8.22-1',
      commit_sha: 'c04d17a',
      author: 'r.okafor',
      message: 'Bump payment SDK to 4.2.1',
      deployed_at: '2026-08-22T09:45:00Z',
      status: 'superseded',
      changed_files: ['package.json', 'package-lock.json'],
      diff: `--- a/package.json
+++ b/package.json
@@ -18,7 +18,7 @@
-    "@acme/payments": "4.1.9",
+    "@acme/payments": "4.2.1",
`,
    },
    {
      id: 'dpl-4c18',
      service: SERVICE,
      version: '2026.8.20-3',
      commit_sha: '55ab0f9',
      author: 'd.novak',
      message: 'Cache tax lookup responses for 60s',
      deployed_at: '2026-08-20T16:10:00Z',
      status: 'superseded',
      changed_files: ['src/checkout/taxCache.ts'],
      diff: `--- /dev/null
+++ b/src/checkout/taxCache.ts
@@ -0,0 +1,9 @@
+export const taxCache = new TTLCache({ ttlMs: 60_000, max: 5_000 });
`,
    },
  ];
}

export function buildIncident(): Incident {
  return {
    id: 'INC-2048',
    title: 'Checkout p95 latency regression',
    service: SERVICE,
    severity: 'SEV-2',
    status: 'investigating',
    summary:
      'Synthetic checkout probe breached its 400ms p95 budget and has stayed above it. ' +
      'Card authorisation success is unaffected; customers see slow checkouts and some 5xx.',
    detected_at: '2026-08-25T15:04:00Z',
    detected_by: 'synthetic-probe/checkout-p95',
    notes: [],
  };
}

export function buildHealth(liveDeploymentId: string): ServiceHealth {
  const regressed = liveDeploymentId === 'dpl-4c21';
  return {
    service: SERVICE,
    status: regressed ? 'degraded' : 'healthy',
    live_deployment_id: liveDeploymentId,
    replicas_ready: regressed ? 6 : 8,
    replicas_desired: 8,
    checks: [
      {
        name: 'liveness',
        ok: true,
        detail: 'all replicas responding to /healthz',
      },
      {
        name: 'readiness',
        ok: !regressed,
        detail: regressed
          ? '2 of 8 replicas failing readiness: upstream call exceeds probe timeout'
          : 'all replicas ready',
      },
      {
        name: 'upstream:tax-provider',
        ok: !regressed,
        detail: regressed
          ? 'connection pool saturated, 3 queued retries per request'
          : 'pool healthy, no queueing',
      },
      {
        name: 'database',
        ok: true,
        detail: 'primary reachable, replication lag 40ms',
      },
    ],
  };
}
